## close 메서드
> ex) InputStream, OutputStream, java.sql.Connection
- Java Application 내에서만 사용되는 자원들이 아닌 운영체제의 자원을 사용하는 것들 (File, Network, DB 등)
- 클라이언트가 직접 close 메서드를 호출해 직접 닫아주어야 한다.

## finalizer
- 클라이언트가 close 메소드를 놓칠 수 있기 때문에 안전망으로 쓰인다.
- 예측할 수 없고, 상황에 따라 위험할 수 있다.
- 아이템 8 참고

## try-finally
```Java
// 자원을 1개 사용할 때
static String firstLineOfFile(String path) throws IOException {
    BufferedReader br = new BufferedReader(new FileReader(path));
    try {
        return br.readLine();
    } finally {
        br.close();
    }
}
```
- 기기에 물리적인 문제가 생긴다고 가정   
    1. firstLineOfFinally 메서드 안의 readLine 메서드에서 예외 던짐
    2. 그 후, close 메서드에서 예외 던짐   
    3. close 메서드 에러가 readLine 메서드 에러를 잡아먹음
    4. close 메서드 에러만 표시되고 readLine 메서드 에러는 표시되지 않음
    
    ```
    // 에러 예시 
    Exception in thread "main" java.lang.NullPointerException // close 예외 
        at org.example.hs.week03.TryFinally.fistLineOfFile
        at org.example.hs.week03.TryFinally.main
    ```
    
    
- 보통 처음 발생한 예외를 중요시 하므로 시스템에서 디버깅이 몹시 어려워짐
- 두번째 예외 대신 첫번째 예외를 기록하도록 코드 수정이 가능하지만 코드가 매우 지저분해짐

```Java
// 자원을 2개 사용할 때
static void copy(String src, String dst) throws IOException {
    InputStream in = new FileInputStream(src);
    try {
        OutputStream out = new FileOutputStream(dst);
        try {
            byte[] buf = new byte[BUFFER_SIZE];
            int n;
            while((n = in.read(buf)) >= 0)
                out.write(buf, 0, n);
        } finally {
            out.close();
        }
    } finally {
        in.close();
    }
}
```
> try-finally 내부에 try-finally 중첩   
> 좋지 못한 코드   


## try-with-resources
> 해당 자원이 AutoCloseable 인터페이스를 구현해야 함   
    ```Java
    // AutoCloseable 인터페이스
    public interface AutoCloseable {
        void close() throws Exception;
    }
    ```
> 많은 자바 라이브러리의 수많은 클래스와 인터페이스에 이미 AutoCloseable이 구현되어있음

``` Java
// try-finally
static String firstLineOfFile(String path) throws IOException {
    BufferedReader br = new BufferedReader(new FileReader(path));
    try {
        return br.readLine();
    } finally {
        br.close();
    }
}

// try-with-resources
static String firstLineOfFile(String path) throws IOException {
    try (BufferedReader br = new BufferedReader(new FileReader(path))) {
        return br.readLine();
    }
}
```

- readLine과 close 호출 양쪽에서 예외가 발생할 경우, close 예외는 숨겨지고 readLine 예외가 기록됨
- 숨겨진 예외들도 스택 추적 내역에 '숨겨졌다(suppressed)'라는 꼬리표를 달고 출력

```
// 예외 예시
Exception in thread "main" java.lang.IllegalArgumentException // readLine 예외
    at org.example.hs.week03.TryWithRes.firstLineOfFile
    at org.example.hs.week03.TryWithRes.main
    Suppressed: java.lang.NullPointerException // close 예외 (Suppressed)
        at org.example.hs.week03.Open.close
        at org.example.hs.week03.TryWithRes.firstLineOfFile
        ... 1 more
```

``` Java
// try-finally
static void copy(String src, String dst) throws IOException {
    InputStream in = new FileInputStream(src);
    try {
        OutputStream out = new FileOutputStream(dst);
        try {
            byte[] buf = new byte[BUFFER_SIZE];
            int n;
            while((n = in.read(buf)) >= 0)
                out.write(buf, 0, n);
        } finally {
            out.close();
        }
    } finally {
        in.close();
    }
}

// try-with-resources
static void copy(String src, String dst) throws IOException {
    try (InputStream in = new FileInputStream(src); OutputSteam out = new FileOutputStream(dst)) {
        byte[] buf = new byte[BUFFER_SIZE];
        int n;
        while((n = in.read(buf)) >= 0)
            out.write(buf, 0, n);
    }
}
```

- 짧고 읽기 수월하다.

    ### Throwable에 추가된 getSuppressed 메서드   
    try-with-resources 상태에서 숨겨진 모든 예외들을 배열로 묶어 반환 
    ```Java
    // Syntax
    public final Throwable[] getSuppressed()
    ```

    ```Java
    // getSuppressed 사용 예시
    public static void testException() throws Exception { 

        Exception suppressed = new ArrayIndexOutOfBoundsException(); 
        final IOException ioe = new IOException();  

        ioe.addSuppressed(suppressed); 
        throw ioe; 
    } 

    public static void main(String[] args) throws Exception {

        try { 
            testException(); 
        } catch (Throwable e) {  
            Throwable[] suppExe = e.getSuppressed(); 

            for (int i = 0; i < suppExe.length; i++) { 
                System.out.println("Suppressed Exceptions:"); 
                System.out.println(suppExe[i]); 
            } 
        } 
    } 
    ```
    ```
    // 출력
    Suppressed Exceptions:
    java.lang.ArrayIndexOutOfBoundsException
    ```

    ### try-with-resources에서 catch절 사용   
    try문을 더 중첩하지 않고도 다수의 예외 처리 가능 

    ```Java
    static String firstLineOfFile(String path, String defaultVal) {
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            return br.readLine();
        } catch (IOException e) {
            return defaultVal;
        }
    }
    ```
    1. try-with-resources를 활용하여 BufferedReader 객체 생성시 예외 체크
    2. try문 안에서의 예외체크(readLine) - catch에서 예외 처리 진행   


## 정리
- 꼭 회수해야 하는 자원을 다룰 때, try-finally 대신 try-with-resources 를 사용
- try-with-resources 를 사용하면 더 짧고 분명해지며, 쉽게 자원 회수 가능 
